### ISSUE TITLE
大佬  这个docker启动的接口文档去哪儿找呀？

### ISSUE THREAD

**Issue by timersun** [lixh00/web-wechat#18]
大佬  这个docker启动的接口文档去哪儿找呀？

**Comment by lixh00** [comment]
莫得，得自己翻代码看

**Comment by timersun** [comment]
![image](https://github.com/user-attachments/assets/93710b0c-f0cb-4572-997a-0d982df32bd2)
厉害啊大佬  哪儿都有你的代码，这个可以通过api调用和回调吗？

**Comment by timersun** [comment]
我想实现api被动收消息并转发，api发送消息给指定的人   类似wxhelper实现的那些功能，这个能实现吗大佬？

**Comment by lixh00** [comment]
我记得好像不支持转发，具体的你可以看`openwechat`的文档

**Comment by timersun** [comment]
好的  谢谢大佬
